build:
  image: tobitheo/gluon-build:0.3
  environment:
    - FORCE_UNSAFE_CONFIGURE=1
  commands:
    - cd ..
    - git clone https://github.com/freifunk-gluon/gluon.git gluon -b v2016.1.4
    - cp -r site gluon/
    - cd gluon
    - if [ -d site/tools ] ; then mv site/tools . ; fi
    - make -j6 update
    - make -j6 GLUON_TARGET=ar71xx-generic
    - cp -r tools ../site/
  cache:
    mount:
      - tools

deploy:
  rsync:
    user: www-data
    host: 10.10.0.186
    port: 22
    source: /drone/src/git.freifunk-hennef.de/Freifunk-Hennef/gluon/output/images/
    target: /var/www/images.freifunk-hennef.de/
    delete: false
    recursive: true

