pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - gluon
    volumes:
      - /var/cache/drone:/cache

  build:
    image: ffhef/docker-buildimage
    volumes:
      - /freifunk/firmware:/firmware
    environment:
      - VERBOSE=
      - MAKE_JOBS=6
      - FORCE_UNSAFE_CONFIGURE=1
      - GLUON_BUILD=v2017.1.4
      - GLUON_TARGETS=ar71xx-generic mpc85xx-generic ar71xx-tiny ar71xx-nand brcm2708-bcm2708 brcm2708-bcm2709
    commands:
      - export BUILDDATE=$( date +%Y%m%d )
      - if [ "$DRONE_BRANCH" != "exp" ] ; then export GLUON_RELEASE=${GLUON_BUILD}-${DRONE_BRANCH}-1.${DRONE_BUILD_NUMBER} ; fi
      - if [ "$DRONE_BRANCH" == "exp" ] ; then export GLUON_RELEASE=${DRONE_BRANCH}-${BUILDDATE}-${DRONE_BUILD_NUMBER} ; fi
      - if [ -d gluon ] ; then cd gluon ; git checkout master ; git reset --hard ; git pull origin master ; git checkout $GLUON_BUILD ; cd .. ; fi
      - if [ ! -d gluon ] ; then git clone https://github.com/freifunk-gluon/gluon.git gluon -b $GLUON_BUILD ; fi
      - rm -rf gluon/site/
      - mkdir -p gluon/site/
      - cp -ar i18n/ site.* gluon/site/
      - if [ "$DRONE_BRANCH" != "exp" ] ; then export AABRANCH=$DRONE_BRANCH ; else export AABRANCH='experimental' ; fi
      - if [ "$DRONE_BRANCH" != "exp" ] ; then sed -i -e "s/branch = 'experimental'/branch = \'$AABRANCH\'/" site/site.conf ; fi
      - cd gluon
      - make -j$MAKE_JOBS update $VERBOSE
      - for GLUON_TARGET in $GLUON_TARGETS ; do make -j$MAKE_JOBS GLUON_TARGET=$GLUON_TARGET GLUON_BRANCH=$AABRANCH $VERBOSE ; done
      - make -j$MAKE_JOBS manifest GLUON_BRANCH=$AABRANCH $VERBOSE
      - mv output/images/ ../images/
      - mkdir -p /firmware/unsigned/
      - cp -r ../images/* /firmware/unsigned/

  positive:
    image: ffhef/docker-curl
    commands:
      - curl "https://services.freifunk-hennef.de/nodered/tg_fw_build/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}/successful"
    when:
      status: success

  negative:
    image: ffhef/docker-curl
    commands:
      - curl "https://services.freifunk-hennef.de/nodered/tg_fw_build/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}/FAILED"
      - tail -100 /tmp/buildlog
    when:
      status: failure

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - gluon
    volumes:
      - /var/cache/drone:/cache

