cache:
  mount:
    - gluon

build:
  image: tobitheo/gluon-build:0.3
  environment:
    - MAKE_JOBS=8
    - FORCE_UNSAFE_CONFIGURE=1
    - GLUON_BUILD=v2016.1.4
    - GLUON_TARGET=ar71xx-generic
  commands:
    - cd ..
    - if [ -d gluon ] ; then cd gluon ; git checkout $GLUON_BUILD ; git pull ; cd .. ; fi
    - if [ ! -d gluon ] ; then git clone https://github.com/freifunk-gluon/gluon.git gluon -b $GLUON_BUILD ; fi
    - cp -r site gluon/
    - cd gluon
    - rm -r site
    - cp -a ../site .
    - make -j$MAKE_JOBS update
    - make clean GLUON_TARGET=$GLUON_TARGET
    - make -j$MAKE_JOBS GLUON_TARGET=$GLUON_TARGET

deploy:
  rsync:
    user: www-data
    host: 10.10.0.186
    port: 22
    source: /drone/src/git.freifunk-hennef.de/Freifunk-Hennef/gluon/output/images/
    target: /var/www/images.freifunk-hennef.de/unsigned/$DRONE_BRANCH/
    delete: false
    recursive: true

