workspace:
  base: /workspace
  path: Freifunk-Hennef/site

pipeline:
  build:
    image: ffhef/docker-buildimage
    volumes:
      - /freifunk/firmware:/firmware
      - /var/cache/drone/gluon:/workspace/Freifunk-Hennef/site/gluon
    environment:
      - VERBOSE=
      - MAKE_JOBS=8
      - FORCE_UNSAFE_CONFIGURE=1
      - GLUON_BUILD=v2017.1.4
      - GLUON_TARGETS=ar71xx-tiny ar71xx-generic ar71xx-nand brcm2708-bcm2708 brcm2708-bcm2709 mpc85xx-generic x86-generic x86-geode x86-64

    commands:
      - if [ "$DRONE_BRANCH" != "exp" ] ; then export GLUON_RELEASE=${GLUON_BUILD}-${DRONE_BRANCH}-1.${DRONE_BUILD_NUMBER} ; fi
      - if [ "$DRONE_BRANCH" = "exp" ] ; then export GLUON_RELEASE=${DRONE_BRANCH}-$( date +%Y%m%d )-${DRONE_BUILD_NUMBER} ; GLUON_TARGETS="ar71xx-tiny ar71xx-generic ar71xx-nand mpc85xx-generic" ; fi
      - if [ -d gluon/.git ] ; then cd gluon ; git checkout master ; git reset --hard ; git pull origin master ; git checkout $GLUON_BUILD ; cd .. ; fi
      - if [ ! -d gluon/.git ] ; then git clone https://github.com/freifunk-gluon/gluon.git gluon -b $GLUON_BUILD ; fi
      - rm -rf gluon/site/
      - mkdir -p gluon/site/
      - cp -ar i18n/ site.* modules gluon/site/
      - if [ "$DRONE_BRANCH" != "exp" ] ; then export AABRANCH=$DRONE_BRANCH ; else export AABRANCH='experimental' ; fi
      - if [ "$DRONE_BRANCH" != "exp" ] ; then sed -i -e "s/branch = 'experimental'/branch = \'$AABRANCH\'/" site/site.conf ; fi
      - cd gluon
      - make update $VERBOSE
      - for GLUON_TARGET in $GLUON_TARGETS ; do echo "--------------------------------------------------------------------------------" ; echo "Building $GLUON_TARGET" ; make -j$MAKE_JOBS GLUON_TARGET=$GLUON_TARGET GLUON_BRANCH=$AABRANCH $VERBOSE ; done
      - make manifest GLUON_BRANCH=$AABRANCH $VERBOSE
      - mkdir -p /firmware/unsigned/
      - cp -r output/images/* /firmware/unsigned/
      - if [ "$DRONE_BRANCH" = "exp" ] ; then ./contrib/sign.sh /firmware/keys/autosign.key /firmware/unsigned/sysupgrade/experimental.manifest && mv /firmware/unsigned/sysupgrade/* /firmware/signed/experimental/sysupgrade/ && mv /firmware/unsigned/factory/* /firmware/signed/experimental/factory/ ; fi

  positive:
    image: ffhef/docker-curl
    commands:
      - curl "https://services.freifunk-hennef.de/nodered/tg_fw_build/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}/successful"
    when:
      status: success

  negative:
    image: ffhef/docker-curl
    commands:
      - curl "https://services.freifunk-hennef.de/nodered/tg_fw_build/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}/FAILED"
    when:
      status: failure

