build:
  image: tobitheo/gluon-build:0.3
  environment:
    - MAKE_JOBS=8
    - FORCE_UNSAFE_CONFIGURE=1
    - GLUON_BUILD=v2016.1.5
    - GLUON_TARGET=ar71xx-generic
  commands:
    - export GLUON_RELEASE=$GLUON_BUILD-$${BRANCH}-1.$$BUILD_NUMBER
    - date
    - cd ..
    - if [ -d gluon ] ; then cd gluon ; git checkout master ; git reset --hard ; git pull origin master ; git checkout $GLUON_BUILD ; cd .. ; fi
    - date
    - if [ ! -d gluon ] ; then git clone https://github.com/freifunk-gluon/gluon.git gluon -b $GLUON_BUILD ; fi
    - date
    - cp -r site gluon/
    - date
    - cd gluon
    - rm -r site
    - cp -a ../site .
    - if [ "$$BRANCH" != "exp" ] ; then export AABRANCH=$$BRANCH ; else export AABRANCH='experimental' ; fi
    - if [ "$$BRANCH" != "exp" ] ; then sed -i -e "s/branch = \'experimental\'/branch = \'$$BRANCH\'/" site/site.conf ; fi
    - cat site/site.conf
    - export
    - date
    - make -j$MAKE_JOBS update
    - date
    - make clean GLUON_TARGET=$GLUON_TARGET
    - date
    - make -j$MAKE_JOBS GLUON_TARGET=$GLUON_TARGET GLUON_BRANCH=$AABRANCH
    - date
    - make manifest GLUON_BRANCH=$AABRANCH
    - date
    - mv output/images/ ../images/
    - date

deploy:
  rsync:
    user: www-data
    host: srv01.freifunk-hennef.de
    port: 22
    source: /drone/src/git.freifunk-hennef.de/Freifunk-Hennef/images/
    target: /var/www/images/unsigned/$$BRANCH/
    delete: false
    recursive: true

