pipeline:
  build:
    image: ffhef/docker-buildimage
    environment:
      - MAKE_JOBS=8
      - FORCE_UNSAFE_CONFIGURE=1
      - GLUON_BUILD=master
      - GLUON_TARGETS=ar71xx-generic mpc85xx-generic ar71xx-tiny ar71xx-mikrotik ar71xx-nand brcm2708-bcm2708 brcm2708-bcm2709 generic mvebu ramips-mt7621 ramips-mt7628 ramips-rt305x sunxi
    commands:
      - export BUILDDATE=$( date +%Y%m%d )
      - export GLUON_RELEASE=${DRONE_BRANCH}-$BUILDDATE
      - echo $GLUON_RELEASE
      - date
      - cd ..
      - if [ -d gluon ] ; then cd gluon ; git checkout master ; git reset --hard ; git pull origin master ; git checkout $GLUON_BUILD ; cd .. ; fi
      - date
      - if [ ! -d gluon ] ; then git clone https://github.com/freifunk-gluon/gluon.git gluon -b $GLUON_BUILD ; fi
      - date
      - cp -r site gluon/
      - date
      - cd gluon
      - rm -r site
      - cp -a ../site .
      - if [ "$DRONE_BRANCH" != "exp" ] ; then export AABRANCH=$DRONE_BRANCH ; else export AABRANCH='experimental' ; fi
      - if [ "$DRONE_BRANCH" != "exp" ] ; then sed -i -e "s/branch = 'experimental'/branch = \'$AABRANCH\'/" site/site.conf ; fi
      - cat site/site.conf
      - export
      - date
      - make -j$MAKE_JOBS update
      - date
      - for GLUON_TARGET in $GLUON_TARGETS ; do make clean GLUON_TARGET=$GLUON_TARGET ; date ; make -j$MAKE_JOBS GLUON_TARGET=$GLUON_TARGET GLUON_BRANCH=$AABRANCH ; done
      - date
      - make manifest GLUON_BRANCH=$AABRANCH
      - date
      - mv output/images/ ../images/
      - date

  deploy:
    image: drillster/drone-rsync
    commands:
      - if [ "$DRONE_BRANCH" != "exp" ] ; then export AABRANCH=$DRONE_BRANCH ; else export AABRANCH='experimental' ; fi
    user: www-data
    hosts: [ "srv01.freifunk-hennef.de" ]
    key: ${DEPLOYKEY}
    source: /drone/src/github.com/Freifunk-Hennef/images/
    target: /var/www/images/unsigned/$AABRANCH/
    delete: false
    recursive: true

  positive:
    image: ffhef/docker-curl
    commands:
      - curl "https://services.freifunk-hennef.de/nodered/tg_fw_build/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}/successful"
    when:
      status: success

  negative:
    image: ffhef/docker-curl
    commands:
      - curl "https://services.freifunk-hennef.de/nodered/tg_fw_build/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}/FAILED"
    when:
      status: failure
