pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - gluon
    volumes:
      - /var/cache/drone:/cache

  build:
    image: ffhef/docker-buildimage
    environment:
      - VERBOSE=
      - MAKE_JOBS=6
      - FORCE_UNSAFE_CONFIGURE=1
      - GLUON_BUILD=v2017.1.3
      - GLUON_TARGETS=ar71xx-generic mpc85xx-generic ar71xx-tiny ar71xx-nand brcm2708-bcm2708 brcm2708-bcm2709
    commands:
      - set -x
      - export BUILDDATE=$( date +%Y%m%d )
      - export GLUON_RELEASE=${DRONE_BRANCH}-$BUILDDATE
      - date
      - cd ..
      - if [ -d gluon ] ; then cd gluon ; git checkout master ; git reset --hard ; git pull origin master ; git checkout $GLUON_BUILD ; cd .. ; fi
      - if [ ! -d gluon ] ; then git clone https://github.com/freifunk-gluon/gluon.git gluon -b $GLUON_BUILD ; fi
      - date
      - cp -r site gluon/
      - cd gluon
      - rm -r site
      - cp -a ../site .
      - if [ "$DRONE_BRANCH" != "exp" ] ; then export AABRANCH=$DRONE_BRANCH ; else export AABRANCH='experimental' ; fi
      - if [ "$DRONE_BRANCH" != "exp" ] ; then sed -i -e "s/branch = 'experimental'/branch = \'$AABRANCH\'/" site/site.conf ; fi
      - cat site/site.conf
      - export
      - date
      - make update $VERBOSE
      - date
      - for GLUON_TARGET in $GLUON_TARGETS ; do make -j$MAKE_JOBS GLUON_TARGET=$GLUON_TARGET GLUON_BRANCH=$AABRANCH $VERBOSE | tee -a /tmp/buildlog ; date ; done
      - make manifest GLUON_BRANCH=$AABRANCH $VERBOSE
      - date
      - mv output/images/ ../images/
      - date

  deploy:
    image: drillster/drone-rsync
    user: www-data
    hosts: [ '10.186.0.128' ]
    key: ${DEPLOYKEY}
    source: /drone/src/github.com/Freifunk-Hennef/images/
    target: /var/www/images/unsigned/${DRONE_BRANCH}/
    delete: false
    recursive: true

  positive:
    image: ffhef/docker-curl
    commands:
      - curl "https://services.freifunk-hennef.de/nodered/tg_fw_build/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}/successful"
    when:
      status: success

  negative:
    image: ffhef/docker-curl
    commands:
      - curl "https://services.freifunk-hennef.de/nodered/tg_fw_build/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}/FAILED"
      - tail -100 /tmp/buildlog
    when:
      status: failure

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - gluon
    volumes:
      - /var/cache/drone:/cache

